# Add user configurations here
# For HyDE to not touch your beloved configurations,
# we added a config file for you to customize HyDE before loading zshrc
# Edit $ZDOTDIR/.user.zsh to customize HyDE before loading zshrc

#  Plugins 
# oh-my-zsh plugins are loaded  in $ZDOTDIR/.user.zsh file, see the file for more information

#  Aliases 
# Override aliases here in '$ZDOTDIR/.zshrc' (already set in .zshenv)

# # Helpful aliases
# alias c='clear'                                                        # clear terminal
# alias l='eza -lh --icons=auto'                                         # long list
# alias ls='eza -1 --icons=auto'                                         # short list
# alias ll='eza -lha --icons=auto --sort=name --group-directories-first' # long list all
# alias ld='eza -lhD --icons=auto'                                       # long list dirs
# alias lt='eza --icons=auto --tree'                                     # list folder as tree
# alias un='$aurhelper -Rns'                                             # uninstall package
# alias up='$aurhelper -Syu'                                             # update system/package/aur
# alias pl='$aurhelper -Qs'                                              # list installed package
# alias pa='$aurhelper -Ss'                                              # list available package
# alias pc='$aurhelper -Sc'                                              # remove unused cache
# alias po='$aurhelper -Qtdq | $aurhelper -Rns -'                        # remove unused packages, also try > $aurhelper -Qqd | $aurhelper -Rsu --print -
# alias vc='code'                                                        # gui code editor
# alias fastfetch='fastfetch --logo-type kitty'

# # Directory navigation shortcuts
# alias ..='cd ..'
# alias ...='cd ../..'
# alias .3='cd ../../..'
# alias .4='cd ../../../..'
# alias .5='cd ../../../../..'

# # Always mkdir a path (this doesn't inhibit functionality to make a single dir)
# alias mkdir='mkdir -p'

#  This is your file 
# Add your configurations here
# export EDITOR=nvim
# export EDITOR=code

# zoxide: replaces `cd` directly (--cmd cd), so it stays a drop-in cd but
# learns frecency over time; also gives `cdi` for an fzf-style interactive
# pick. Bound to `cd` rather than the default `z`/`zi` to avoid clashing
# with HyDE's own rupa/z zinit plugin, which already owns those names.
command -v zoxide >/dev/null && eval "$(zoxide init zsh --cmd cd)"

# unset -f command_not_found_handler # Uncomment to prevent searching for commands not found in package manager

#  Aliases (personal)
alias reload="source \"${ZDOTDIR:-$HOME}/.zshrc\""

# claudio [dir] [claude args...] -- runs in the current dir, or in [dir] if given
claudio() {
    if [[ -d "$1" ]]; then
        cd "$1" || return 1
        shift
    fi
    echo "claudio -> $PWD"
    claude --dangerously-skip-permissions "$@"
}

# dev <project> -- tmux session named after the project, in ~/projects/<project>, launches claudio
# reattaches to an existing session if already running (persists across mosh/ssh drops)
dev() {
    local name="$1"; shift
    [[ -z "$name" ]] && { echo "usage: dev <project-name>" >&2; return 1; }
    local dir="$HOME/Projects/$name"
    [[ -d "$dir" ]] || { echo "dev: $dir not found" >&2; return 1; }
    if tmux has-session -t "$name" 2>/dev/null; then
        tmux attach -t "$name"
    else
        tmux new-session -s "$name" -c "$dir" "zsh -ic 'claudio $*'"
    fi
}

# fuzzy-find a file by (partial) name under $HOME, pick from matches, and open it
# e.g. `open list.txt` offers ~/market/list_market.txt among the matches
open() {
    local matches match
    matches=$(fd -H -t f -i "$1" ~ 2>/dev/null)
    if [[ -z "$matches" ]]; then
        echo "open: no match for '$1'" >&2
        return 1
    fi
    match=$(echo "$matches" | fzf --prompt="open> " --select-1)
    [[ -n "$match" ]] && xdg-open "$match"
}

# --- bat / delta: "Wallbash" is the dynamic theme kept in sync with
# whichever HyDE theme is active (dotfiles/.config/hyde/wallbash/theme/bat.dcol) ---
export BAT_THEME="Wallbash"

# --- fzf colors + zsh-syntax-highlighting styles ---
# Generated by wallbash from the active HyDE theme (see
# dotfiles/.config/hyde/wallbash/theme/zsh-colors.dcol) — not edited here so
# a `hydectl theme set` stays the single source of truth. Only reached by
# *new* shells: FZF_DEFAULT_OPTS and ZSH_HIGHLIGHT_STYLES are read once at
# shell init, so an already-open terminal needs a fresh tab/`exec zsh` to
# pick up a theme switch.
[[ -f "$HOME/.config/zsh/wallbash-colors.zsh" ]] && source "$HOME/.config/zsh/wallbash-colors.zsh"
