#!/usr/bin/env bash
# calcurse only supports 8 ANSI names + "default", one global fg-on-bg pair
# for the whole UI (no per-element theming at all). color.set.sh exports
# every dcol_* variable before running this script, so it reads them
# directly instead of via a sed placeholder substitution that can't
# pick a nearest-named-color.
set -euo pipefail

nearest_ansi() {
    local hex="${1#\#}"
    local r=$((16#${hex:0:2})) g=$((16#${hex:2:2})) b=$((16#${hex:4:2}))
    # Euclidean distance in RGB space to each of the 6 non-neutral ANSI colors.
    local best="red" best_d=999999
    local -A named=(
        [red]="255 0 0" [green]="0 255 0" [yellow]="255 255 0"
        [blue]="0 0 255" [magenta]="255 0 255" [cyan]="0 255 255"
    )
    local name rgb nr ng nb d
    for name in "${!named[@]}"; do
        rgb=(${named[$name]})
        nr=${rgb[0]}; ng=${rgb[1]}; nb=${rgb[2]}
        d=$(( (r-nr)*(r-nr) + (g-ng)*(g-ng) + (b-nb)*(b-nb) ))
        if (( d < best_d )); then best_d=$d; best=$name; fi
    done
    echo "$best"
}

out="${HOME}/.config/calcurse/conf"
mkdir -p "$(dirname "$out")"

accent="$(nearest_ansi "${dcol_4xa9:-ff6188}")"

cat >"$out" <<EOF
# Generated by wallbash from the active HyDE theme — do not edit directly,
# edit dotfiles/.config/hyde/wallbash/scripts/calcurse.sh instead.
# calcurse only supports 8 ANSI names + "default", one global pair for the
# whole UI -- this picks the nearest ANSI name to the active theme's red/
# pink accent (dcol_4xa9).
appearance.theme=$accent on default
EOF
