#!/usr/bin/env bash
# cmus has no hex support, only the xterm 256-color palette index -- see
# docs/monokai-pro-palette.md "Tools without hex support". color.set.sh
# exports every dcol_* variable before running this script, so it reads
# them directly instead of via a sed placeholder substitution that can't
# do the hex->256 math.
set -euo pipefail

hex_to_256() {
    local hex="${1#\#}"
    local r=$((16#${hex:0:2})) g=$((16#${hex:2:2})) b=$((16#${hex:4:2}))
    # Prefer the grayscale ramp (232-255) when r/g/b are close together --
    # it has finer steps than the 6x6x6 cube can offer for near-neutral tones.
    local maxc=$((r > g ? r : g)); maxc=$((maxc > b ? maxc : b))
    local minc=$((r < g ? r : g)); minc=$((minc < b ? minc : b))
    if ((maxc - minc < 10)); then
        local gray=$(( (r + g + b) / 3 ))
        if ((gray < 8)); then echo 16; return; fi
        if ((gray > 238)); then echo 231; return; fi
        echo $(( 232 + (gray - 8) * 24 / 231 ))
        return
    fi
    local cr=$(((r * 5 + 127) / 255)) cg=$(((g * 5 + 127) / 255)) cb=$(((b * 5 + 127) / 255))
    echo $((16 + 36 * cr + 6 * cg + cb))
}

out="${HOME}/.config/cmus/wallbash.theme"
mkdir -p "$(dirname "$out")"

bg="$(hex_to_256 "${dcol_pry1:-2d2a2e}")"
panel="$(hex_to_256 "${dcol_pry2:-221f22}")"
fg="$(hex_to_256 "${dcol_txt1:-fcfcfa}")"
accent="$(hex_to_256 "${dcol_2xa7:-ab9df2}")"
muted="$(hex_to_256 "${dcol_1xa9:-939293}")"
red="$(hex_to_256 "${dcol_4xa9:-ff6188}")"
cyan="$(hex_to_256 "${dcol_3xa7:-78dce8}")"

cat >"$out" <<EOF
# Generated by wallbash from the active HyDE theme — do not edit directly,
# edit dotfiles/.config/hyde/wallbash/scripts/cmus.sh instead.
set color_win_bg=$panel
set color_win_fg=$fg
set color_win_dir=$cyan

set color_win_title_bg=$bg
set color_win_title_fg=$fg

set color_win_sel_bg=$bg
set color_win_sel_fg=$fg
set color_win_cur=$accent
set color_win_cur_sel_bg=$accent
set color_win_cur_sel_fg=$panel

set color_win_inactive_sel_bg=default
set color_win_inactive_sel_fg=$muted
set color_win_inactive_cur_sel_bg=default
set color_win_inactive_cur_sel_fg=$muted

set color_statusline_bg=$bg
set color_statusline_fg=$fg
set color_statusline_progress_bg=$accent
set color_statusline_progress_fg=$panel

set color_titleline_bg=$accent
set color_titleline_fg=$panel

set color_cmdline_bg=default
set color_cmdline_fg=$fg

set color_error=$red
set color_info=$fg
set color_separator=$cyan
EOF
