#!/usr/bin/env bash
# endcord's theme uses the ncurses xterm-256 palette index (fg,bg,[attr]
# arrays, python literal_eval'd from a [theme] INI section) -- see
# /usr/share/doc/endcord/configuration.md's "Theme" section for the key
# list and https://github.com/mzivic7/endcord's config.py for the parsing
# (literal_eval + color.parse_color()). color.set.sh exports every dcol_*
# variable before running this script.
set -euo pipefail

hex_to_256() {
    local hex="${1#\#}"
    local r=$((16#${hex:0:2})) g=$((16#${hex:2:2})) b=$((16#${hex:4:2}))
    local maxc=$((r > g ? r : g)); maxc=$((maxc > b ? maxc : b))
    local minc=$((r < g ? r : g)); minc=$((minc < b ? minc : b))
    if ((maxc - minc < 10)); then
        local gray=$(( (r + g + b) / 3 ))
        if ((gray < 8)); then echo 16; return; fi
        if ((gray > 238)); then echo 231; return; fi
        echo $(( 232 + (gray - 8) * 24 / 231 ))
        return
    fi
    local cr=$(((r * 5 + 127) / 255)) cg=$(((g * 5 + 127) / 255)) cb=$(((b * 5 + 127) / 255))
    echo $((16 + 36 * cr + 6 * cg + cb))
}

out="${HOME}/.config/endcord/Themes/wallbash-theme.ini"
mkdir -p "$(dirname "$out")"

fg="$(hex_to_256 "${dcol_txt1:-fcfcfa}")"
dark="$(hex_to_256 "${dcol_pry1:-2d2a2e}")"
muted="$(hex_to_256 "${dcol_1xa9:-939293}")"
accent="$(hex_to_256 "${dcol_2xa7:-ab9df2}")"
cyan="$(hex_to_256 "${dcol_3xa7:-78dce8}")"
green="$(hex_to_256 "${dcol_2xa9:-a9dc76}")"
red="$(hex_to_256 "${dcol_4xa9:-ff6188}")"
sel_bg="$(hex_to_256 "${dcol_pry3:-403e41}")"
panel_bg="$(hex_to_256 "${dcol_pry2:-221f22}")"

cat >"$out" <<EOF
# Generated by wallbash from the active HyDE theme — do not edit directly,
# edit dotfiles/.config/hyde/wallbash/scripts/endcord.sh instead.
[theme]
color_default = [-1, -1]
color_green = [$green, -1]
color_orange = [$accent, -1]
color_red = [$red, -1]
color_chat_mention = [-2, $panel_bg]
color_chat_blocked = [$muted, -1]
color_chat_deleted = [$red, -1]
color_chat_pending = [$muted, -1]
color_chat_selected = [$dark, $accent]
color_chat_separator = [$muted, -1, "i"]
color_chat_standout = [$accent, $panel_bg]
color_chat_edited = [$muted, -1]
color_chat_url = [$cyan, -1, "u"]
color_chat_spoiler = [$panel_bg, $panel_bg]
color_chat_code = [$fg, $panel_bg]
color_status_line = [$dark, $accent]
color_extra_line = [$dark, $muted]
color_title_line = [$dark, $accent]
color_subtitle_line = [$muted, -1]
color_extra_window = [-1, -1]
color_extra_window_low = [$muted, -1]
color_extra_window_standout = [$accent, -1]
color_prompt = [$fg, -1]
color_input_line = [$fg, -1]
color_cursor = [$dark, $accent]
color_scrollbar = [-1, -1]
color_misspelled = [$accent, -1]
color_tree_default = [$fg, -1]
color_tree_category = [$accent, -1]
color_tree_server = [$accent, -1]
color_tree_selected = [$dark, $accent]
color_tree_muted = [$muted, -1]
color_tree_active = [$fg, $panel_bg]
color_tree_unseen = [-2, -2, "b"]
color_tree_mentioned = [$red, -1]
color_tree_active_mentioned = [$red, $panel_bg]
color_tree_selected_mentioned = [$dark, $red]
EOF
