#!/usr/bin/env bash
# Firefox's chrome (toolbar/tabs/urlbar) is themed via userChrome.css, a
# real documented mechanism (support.mozilla.org) gated behind the
# toolkit.legacyUserProfileCustomizations.stylesheets pref. Neither file
# can be a plain wallbash *.dcol template: both live under a *randomized*
# profile directory name Firefox generates at profile-creation time
# (e.g. gd5q6is6.default-release), so the destination path has to be
# resolved at apply-time, not hardcoded. This mirrors the profile
# resolution the old scripts/apply-firefox-theme.sh did before this repo's
# theming went fully dynamic. color.set.sh exports every dcol_* variable
# before running this script.
set -euo pipefail

firefox_dir=""
for candidate in "${XDG_CONFIG_HOME:-$HOME/.config}/mozilla/firefox" "$HOME/.mozilla/firefox"; do
    [[ -f "$candidate/profiles.ini" ]] && { firefox_dir="$candidate"; break; }
done
[[ -z "$firefox_dir" ]] && exit 0

# installs.ini's Default= is the current install's actual active profile
# (profiles.ini can list several profiles; this is the one Firefox itself
# picked). Falls back to profiles.ini's Default=1 [ProfileN] entry if
# installs.ini is missing (older Firefox versions, or a fresh profile
# that hasn't been launched with this exact install yet).
profile_path=""
if [[ -f "$firefox_dir/installs.ini" ]]; then
    profile_path="$(grep -m1 '^Default=' "$firefox_dir/installs.ini" | cut -d= -f2-)"
fi
if [[ -z "$profile_path" ]]; then
    profile_path="$(awk -F= '
        /^\[Profile/ { in_profile=1; path=""; is_default=0 }
        in_profile && /^Path=/ { path=$2 }
        in_profile && /^Default=1/ { is_default=1 }
        in_profile && /^$/ && is_default { print path; exit }
        END { if (is_default) print path }
    ' "$firefox_dir/profiles.ini")"
fi
[[ -z "$profile_path" ]] && exit 0

profile_dir="$firefox_dir/$profile_path"
[[ -d "$profile_dir" ]] || exit 0

mkdir -p "$profile_dir/chrome"

cat >"$profile_dir/user.js" <<'EOF'
// Required for userChrome.css to take effect (support.mozilla.org) --
// generated by wallbash, see dotfiles/.config/hyde/wallbash/scripts/firefox.sh
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
EOF

cat >"$profile_dir/chrome/userChrome.css" <<EOF
/* Generated by wallbash from the active HyDE theme — do not edit
   directly, edit dotfiles/.config/hyde/wallbash/scripts/firefox.sh
   instead. Toolbar/tab bar/urlbar chrome only. Selectors are Firefox's
   long-stable chrome DOM ids/classes. */

:root {
  --wallbash-bg: #${dcol_pry1:-2d2a2e};
  --wallbash-bg-darker: #${dcol_pry2:-221f22};
  --wallbash-fg: #${dcol_txt1:-fcfcfa};
  --wallbash-dim: #${dcol_1xa9:-939293};
  --wallbash-accent: #${dcol_4xa9:-ff6188};
  --wallbash-accent2: #${dcol_2xa7:-ab9df2};
}

#navigator-toolbox,
#TabsToolbar,
#nav-bar {
  background-color: var(--wallbash-bg) !important;
  color: var(--wallbash-fg) !important;
}

.tabbrowser-tab[selected="true"] .tab-background {
  background-color: var(--wallbash-bg-darker) !important;
  border-bottom: 2px solid var(--wallbash-accent2) !important;
}

.tabbrowser-tab .tab-label {
  color: var(--wallbash-fg) !important;
}

#urlbar,
#searchbar {
  background-color: var(--wallbash-bg-darker) !important;
  color: var(--wallbash-fg) !important;
}

#urlbar-background {
  background-color: var(--wallbash-bg-darker) !important;
  border-color: var(--wallbash-dim) !important;
}

#urlbar[focused="true"] #urlbar-background {
  border-color: var(--wallbash-accent2) !important;
}

toolbar#PersonalToolbar {
  background-color: var(--wallbash-bg) !important;
}

#sidebar-box {
  background-color: var(--wallbash-bg) !important;
  color: var(--wallbash-fg) !important;
}
EOF
