#!/usr/bin/env bash
# newsboat has no hex support, only named-8 ANSI colors or colorN (256
# palette index). color.set.sh exports every dcol_* variable before
# running this script, so it reads them directly instead of via a sed
# placeholder substitution that can't do the hex->256 math.
set -euo pipefail

hex_to_256() {
    local hex="${1#\#}"
    local r=$((16#${hex:0:2})) g=$((16#${hex:2:2})) b=$((16#${hex:4:2}))
    local maxc=$((r > g ? r : g)); maxc=$((maxc > b ? maxc : b))
    local minc=$((r < g ? r : g)); minc=$((minc < b ? minc : b))
    if ((maxc - minc < 10)); then
        local gray=$(( (r + g + b) / 3 ))
        if ((gray < 8)); then echo 16; return; fi
        if ((gray > 238)); then echo 231; return; fi
        echo $(( 232 + (gray - 8) * 24 / 231 ))
        return
    fi
    local cr=$(((r * 5 + 127) / 255)) cg=$(((g * 5 + 127) / 255)) cb=$(((b * 5 + 127) / 255))
    echo $((16 + 36 * cr + 6 * cg + cb))
}

out="${HOME}/.config/newsboat/config"
mkdir -p "$(dirname "$out")"

bg="$(hex_to_256 "${dcol_pry1:-2d2a2e}")"
panel="$(hex_to_256 "${dcol_pry2:-221f22}")"
fg="$(hex_to_256 "${dcol_txt1:-fcfcfa}")"
accent="$(hex_to_256 "${dcol_2xa7:-ab9df2}")"
green="$(hex_to_256 "${dcol_2xa9:-a9dc76}")"
yellow="$(hex_to_256 "${dcol_3xa9:-ffd866}")"

cat >"$out" <<EOF
# Generated by wallbash from the active HyDE theme — do not edit directly,
# edit dotfiles/.config/hyde/wallbash/scripts/newsboat.sh instead.
color background         default        color$bg
color listnormal         color$fg       color$bg
color listfocus          color$bg       color$accent   bold
color listnormal_unread  color$yellow   color$bg       bold
color listfocus_unread   color$bg       color$green    bold
color info               color$fg       color$panel
color title               color$green   color$bg       bold
color article             color$fg      color$bg
color end-of-text-marker  color$panel   color$bg
EOF
