#!/usr/bin/env bash
# taskwarrior has no hex support (rgbRGB cube notation only, digits 0-5 per
# channel). color.set.sh exports every dcol_* variable (`set -a; source "$dcol_file"`)
# before running this script, so it reads them directly instead of via a
# sed placeholder substitution that can't do the hex->cube math.
set -euo pipefail

hex_to_rgbcube() {
    local hex="${1#\#}"
    local r=$((16#${hex:0:2})) g=$((16#${hex:2:2})) b=$((16#${hex:4:2}))
    local cr=$(((r * 5 + 127) / 255)) cg=$(((g * 5 + 127) / 255)) cb=$(((b * 5 + 127) / 255))
    printf 'rgb%d%d%d' "$cr" "$cg" "$cb"
}

out="${HOME}/.config/task/taskrc"
mkdir -p "$(dirname "$out")"

pry1="$(hex_to_rgbcube "${dcol_pry1:-2d2a2e}")"     # background
pry2="$(hex_to_rgbcube "${dcol_pry2:-221f22}")"     # panel/background-darker
txt1="$(hex_to_rgbcube "${dcol_txt1:-fcfcfa}")"     # foreground
muted="$(hex_to_rgbcube "${dcol_1xa9:-939293}")"    # dimmed gray
red="$(hex_to_rgbcube "${dcol_4xa9:-ff6188}")"
green="$(hex_to_rgbcube "${dcol_2xa9:-a9dc76}")"
yellow="$(hex_to_rgbcube "${dcol_3xa9:-ffd866}")"
cyan="$(hex_to_rgbcube "${dcol_3xa7:-78dce8}")"
purple="$(hex_to_rgbcube "${dcol_2xa7:-ab9df2}")"

cat >"$out" <<EOF
# Generated by wallbash from the active HyDE theme — do not edit directly,
# edit dotfiles/.config/hyde/wallbash/scripts/taskwarrior.sh instead.
color.label=
color.header=$purple
color.footnote=$muted
color.warning=bold $yellow
color.error=white on $red

color.active=$txt1 on $pry1
color.completed=$muted
color.deleted=$muted
color.blocked=white on $pry2
color.blocking=black on $muted

color.due.today=$yellow
color.due=$cyan
color.overdue=$red

color.tag.next=$green
color.tagged=$cyan
color.project.none=

color.uda.priority.H=$red
color.uda.priority.M=$yellow
color.uda.priority.L=$green

color.recurring=$cyan
color.scheduled=on $pry2

color.undo.after=$green
color.undo.before=$red
EOF
