#!/usr/bin/env bash
# tremc's [Colors] section only accepts "default" or one of the eight
# curses colors (Black/White/Red/Green/Blue/Cyan/Yellow/Magenta), no hex --
# confirmed against the shipped settings.cfg at github.com/tremc/tremc.
# Everything else in this file is tremc's own out-of-box sane defaults
# (localhost:9091, standard sort/filter/keybindings), not user-specific
# data, so unlike jrnl this can be generated whole. color.set.sh exports
# every dcol_* variable before running this script.
set -euo pipefail

nearest_ansi() {
    local hex="${1#\#}"
    local r=$((16#${hex:0:2})) g=$((16#${hex:2:2})) b=$((16#${hex:4:2}))
    local best="red" best_d=999999
    local -A named=(
        [red]="255 0 0" [green]="0 255 0" [yellow]="255 255 0"
        [blue]="0 0 255" [magenta]="255 0 255" [cyan]="0 255 255"
        [white]="255 255 255" [black]="0 0 0"
    )
    local name rgb nr ng nb d
    for name in "${!named[@]}"; do
        rgb=(${named[$name]})
        nr=${rgb[0]}; ng=${rgb[1]}; nb=${rgb[2]}
        d=$(( (r-nr)*(r-nr) + (g-ng)*(g-ng) + (b-nb)*(b-nb) ))
        if (( d < best_d )); then best_d=$d; best=$name; fi
    done
    echo "$best"
}

out="${HOME}/.config/tremc/settings.cfg"
mkdir -p "$(dirname "$out")"

green="$(nearest_ansi "${dcol_2xa9:-a9dc76}")"
cyan="$(nearest_ansi "${dcol_3xa7:-78dce8}")"
purple="$(nearest_ansi "${dcol_2xa7:-ab9df2}")"
yellow="$(nearest_ansi "${dcol_3xa9:-ffd866}")"
red="$(nearest_ansi "${dcol_4xa9:-ff6188}")"
orange="$(nearest_ansi "${dcol_1xa7:-fc9867}")"

cat >"$out" <<EOF
# Generated by wallbash from the active HyDE theme — do not edit directly,
# edit dotfiles/.config/hyde/wallbash/scripts/tremc.sh instead.
[Connection]
password =
username =
port = 9091
host = localhost
path = /transmission/rpc
ssl = False

[Sorting]
order = name

[Filtering]
filter =
invert = False

[Misc]
lines_per_torrent = 3
torrentname_is_progressbar = True
file_viewer = xdg-open %%s
file_open_in_terminal = True
view_selected = False
rdns = True
geoip_database = /xyz
torrent_numbers = True
profile =
x_selection = clipboard

[Colors]
title_seed = bg:$green,fg:black
title_download = bg:$cyan,fg:black
title_idle = bg:$purple,fg:black
title_verify = bg:$orange,fg:black
title_paused = bg:default,fg:default
title_error = bg:$red,fg:default
download_rate = bg:default,fg:$cyan
upload_rate = bg:default,fg:$red
eta+ratio = bg:default,fg:default
filter_status = bg:default,fg:$red
multi_filter_status = bg:default,fg:$cyan
dialog = bg:default,fg:default
dialog_important = bg:default,fg:$red
file_prio_high = bg:default,fg:$red
file_prio_normal = bg:default,fg:default
file_prio_low = bg:default,fg:$yellow
file_prio_off = bg:default,fg:$cyan

[Profiles]
profile0 =

[ListKeys]
backslash = select_search_torrent_fulltext
gt = select_search_torrent_regex_fulltext
y = toggle_torrent_numbers

[DetailsKeys]
y = view_file

[CommonKeys]
Y = verify_torrent
v = move_torrent
EOF
