[theme]
name = "catppuccin-mocha-mauve"

[colors]
AlertInfo = "#a6e3a1"
AlertWarn = "#ff9500"
AlertError = "#f38ba8"
Annotation = "#ff6a00"
Base = "#ffedd5"
Guidance = "#a8703f"
Important = "#f38ba8"
Title = "#ff6a00"
