[theme]
background = "#0d0704"
primary = "#ffedd5"
secondary = "#ff8c3d"
title = "#ff6a00"
playing = "#a6e3a1"
playing_bg = "#0d0704"
highlight = "#ffedd5"
highlight_bg = "#746292"
playing_selected = "#a6e3a1"
error = "#0d0704"
error_bg = "#f38ba8"
statusbar = "#ff6a00"
statusbar_bg = "#1f120a"
statusbar_progress = "#ff6a00"
cmdline = "#ff6a00"
cmdline_bg = "#0a0503"
