font_family      CaskaydiaCove Nerd Font
font_size        11.0

background_opacity 0.68
background_blur    32

# Catppuccin Mocha (https://github.com/catppuccin/kitty)
foreground              #ffedd5
background              #0d0704
selection_foreground    #0d0704
selection_background    #ffcf9c

cursor                  #ffcf9c
cursor_text_color       #0d0704

scrollbar_handle_color  #a8703f
scrollbar_track_color   #2e1c0f

url_color               #ffcf9c

active_border_color     #ffd9a0
inactive_border_color   #6b4a30
bell_border_color       #F9E2AF

wayland_titlebar_color system
macos_titlebar_color   system

active_tab_foreground   #060302
active_tab_background   #ff6a00
inactive_tab_foreground #ffedd5
inactive_tab_background #0a0503
tab_bar_background      #060302

mark1_foreground #0d0704
mark1_background #ffd9a0
mark2_foreground #0d0704
mark2_background #ff6a00
mark3_foreground #0d0704
mark3_background #ff7a1a

color0  #2e1c0f
color1  #F38BA8
color2  #A6E3A1
color3  #F9E2AF
color4  #ffc266
color5  #ff9500
color6  #ff8c3d
color7  #e0a465
color8  #3d2716
color9  #F38BA8
color10 #A6E3A1
color11 #F9E2AF
color12 #ffc266
color13 #ff9500
color14 #ff8c3d
color15 #c98b52

cursor_shape block
cursor_blink_interval 0

allow_remote_control yes
listen_on unix:/tmp/kitty-{kitty_pid}
