gui:
  theme:
    activeBorderColor:
      - '#ff6a00'
      - bold
    inactiveBorderColor:
      - '#c98b52'
    searchingActiveBorderColor:
      - '#f9e2af'
    optionsTextColor:
      - '#ffc266'
    selectedLineBgColor:
      - '#1f120a'
    inactiveViewSelectedLineBgColor:
      - '#6b4a30'
    cherryPickedCommitFgColor:
      - '#ff6a00'
    cherryPickedCommitBgColor:
      - '#2e1c0f'
    markedBaseCommitFgColor:
      - '#ffc266'
    markedBaseCommitBgColor:
      - '#f9e2af'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#ffedd5'

  authorColors:
    '*': '#ffd9a0'
