---
- name: Apply chezmoi source state
  ansible.builtin.command: chezmoi init --source "{{ playbook_dir }}/../chezmoi" --apply --force
  become: true
  become_user: "{{ invoking_user }}"
  environment:
    HOME: "{{ invoking_home }}"
