[theme]
background         = "#2d2a2e"
primary            = "#fcfcfa"
secondary          = "#939293"
title              = "#a9dc76"
playing            = "#a9dc76"
playing_selected   = "#78dce8"
playing_bg         = "#221f22"
highlight          = "#fcfcfa"
highlight_bg       = "#221f22"
error              = "#fcfcfa"
error_bg           = "#ff6188"
statusbar          = "#2d2a2e"
statusbar_progress = "#a9dc76"
statusbar_bg       = "#221f22"
cmdline            = "#fcfcfa"
cmdline_bg         = "#2d2a2e"
search_match       = "#fc9867"
