[theme]
name = "monokai-pro"

[colors]
AlertInfo      = "#78dce8"
AlertWarn      = "#ffd866"
AlertError     = "#ff6188"
Annotation     = "#939293"
Base           = "#fcfcfa"
Guidance       = "#ab9df2"
Important      = "#fc9867"
Title          = "#a9dc76"
Muted          = "#939293"
SyntaxCommand  = "#78dce8"
SyntaxFlag     = "#fc9867"
SyntaxString   = "#ffd866"
SyntaxVariable = "#ab9df2"
SyntaxOperator = "#ff6188"
SyntaxComment  = "#939293"
