font_family      CaskaydiaCove Nerd Font
font_size        11.0

background_opacity 0.68
background_blur    32

# Orange Neon Glass
foreground              #E8E8E8
background              #0A0A0A
selection_foreground    #0A0A0A
selection_background    #FF7A00

cursor                  #FF7A00
cursor_text_color       #0A0A0A

scrollbar_handle_color  #FF9F40
scrollbar_track_color   #3A3A3A

url_color               #FF9F40

active_border_color     #FFB768
inactive_border_color   #3A3A3A
bell_border_color       #FFB347

wayland_titlebar_color system
macos_titlebar_color   system

active_tab_foreground   #0A0A0A
active_tab_background   #FF7A00
inactive_tab_foreground #E8E8E8
inactive_tab_background #0A0A0A
tab_bar_background      #0A0A0A

mark1_foreground #0A0A0A
mark1_background #FFB768
mark2_foreground #0A0A0A
mark2_background #FF9F40
mark3_foreground #0A0A0A
mark3_background #FF6A33

color0  #0A0A0A
color1  #FF4500
color2  #B8D18A
color3  #FFB347
color4  #6E6E6E
color5  #FF9F40
color6  #C9C9C9
color7  #E8E8E8
color8  #3A3A3A
color9  #FF6A33
color10 #CFE3AE
color11 #FFC670
color12 #9A9A9A
color13 #FFB768
color14 #E8E8E8
color15 #FFFFFF

cursor_shape block
cursor_blink_interval 0
