### Monokai Pro colors
text_color=FCFCFA
background_color=2D2A2E
gpu_color=A9DC76
cpu_color=78DCE8
vram_color=AB9DF2
ram_color=FF6188
engine_color=FC9867
io_color=AB9DF2
frametime_color=A9DC76
media_player_color=FCFCFA
wine_color=FC9867
battery_color=FFD866
network_color=FF6188
horizontal_separator_color=939293
gpu_load_color=A9DC76,FFD866,FF6188
cpu_load_color=A9DC76,FFD866,FF6188
fps_color=FF6188,FFD866,A9DC76
