# Monokai Pro theme for btop
# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"

theme[main_bg]="#2d2a2e"
theme[main_fg]="#fcfcfa"
theme[title]="#fcfcfa"
theme[hi_fg]="#ff6188"
theme[selected_bg]="#ab9df2"
theme[selected_fg]="#2d2a2e"
theme[inactive_fg]="#939293"
theme[graph_text]="#939293"
theme[proc_misc]="#a9dc76"
theme[cpu_box]="#939293"
theme[mem_box]="#939293"
theme[net_box]="#939293"
theme[proc_box]="#939293"
theme[div_line]="#221f22"

theme[temp_start]="#78dce8"
theme[temp_mid]="#ffd866"
theme[temp_end]="#ff6188"

theme[cpu_start]="#a9dc76"
theme[cpu_mid]="#ffd866"
theme[cpu_end]="#ff6188"

theme[free_start]="#221f22"
theme[free_mid]="#78dce8"
theme[free_end]="#a9dc76"

theme[cached_start]="#221f22"
theme[cached_mid]="#78dce8"
theme[cached_end]="#78dce8"

theme[available_start]="#221f22"
theme[available_mid]="#ffd866"
theme[available_end]="#fc9867"

theme[used_start]="#221f22"
theme[used_mid]="#ab9df2"
theme[used_end]="#ff6188"

theme[download_start]="#221f22"
theme[download_mid]="#ab9df2"
theme[download_end]="#78dce8"

theme[upload_start]="#221f22"
theme[upload_mid]="#fc9867"
theme[upload_end]="#ff6188"
